biotechwebsite/biotech/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.htmlrender, name='htmlrender'),

    path('htmlrender/<int:question_id>/',
         views.htmlrender, name='htmlrender_with_id'),

    path('projects/', views.projectsrender, name='projectsrender'),

    path('contact/', views.contactrender, name='contactrender'),

    path('faculty/', views.facultyrender, name='facultyrender'),

    path('collaborators/', views.collabrender, name='collabrender'),

    path('mission/', views.missionrender, name='missionrender'),

    path('question/new/', views.question_create_view, name='create_question'),

    path('question/<int:question_id>/answer/',
         views.answer_create_view, name='create_answer'),

    path('genechat/', views.generender, name='generender'),

    path('profile/', views.profilerender, name='profilerender'),

    # path('signup/', views.RegisterView.as_view(), name='users-register')

]

biotechwebsite/biotechwebsite/urls.py
from django.contrib import admin
from django.urls import path, include
import os
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('biotech.urls')),
    path('', include('register.urls')),

    # Maybe later, I will delete below line of code. it is duplicated
    path('', include('django.contrib.auth.urls')),
]

biotechwebsite/biotech/models.py
from django.db import models
from django.contrib.auth.models import User


class Question(models.Model):
    title = models.CharField(max_length=200)
    content = models.TextField()
    created_by = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='created_questions')
    given_to = models.ForeignKey(
        User, unique=False, on_delete=models.CASCADE, related_name='received_questions', null=True)
    posted_at = models.DateTimeField(auto_now_add=True)


class Answer(models.Model):
    content = models.TextField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    posted_at = models.DateTimeField(auto_now_add=True)


class QuestionFile(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    file = models.FileField(upload_to='questions_files/')


class AnswerFile(models.Model):
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE)
    file = models.FileField(upload_to='answers_files/')


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # avatar = models.ImageField(
    #     default='default.jpg', upload_to='profile_images')
    bio = models.TextField()

    def __str__(self):
        return self.user.username

biotechwebsite/biotech/forms.py
from django import forms
from .models import Question, Answer
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group

class QuestionForm(forms.ModelForm):
    file_field = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}), required=False)

    class Meta:
        model = Question
        fields = ['title', 'content']


class AnswerForm(forms.ModelForm):
    file_field = forms.FileField(widget=forms.ClearableFileInput(
        attrs={'multiple': True}), required=False)

    class Meta:
        model = Answer
        fields = ['content']

biotechwebsite/biotech/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy
from .forms import Question, Answer, QuestionForm, AnswerForm
from .models import Question, Answer, QuestionFile, AnswerFile
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.views import View



def htmlrender(request, question_id=None):
    content = {
        'title': 'Welcome to the cutting-edge intersection of computer science and biotechnology at the University of Washington Bothell!',
        'paragraphs': [
            'Our passionate team of researchers and computer scientists is dedicated to exploring and advancing the fields of bioinformatics, systems biology, and computational biology. By harnessing the power of mathematics, statistics, computer science, and engineering, we develop innovative algorithms and sophisticated software programs to delve deep into the vast, complex world of biological data.',
            'The management and analysis of intricate biological data sets present both an immense challenge and an extraordinary research opportunity. As such, our primary research focus lies in pattern recognition within bioinformatics, specifically in the realm of biological motif analysis. Through our work, we strive to unveil hidden patterns, discover meaningful insights, and unlock the full potential of biological data, ultimately contributing to the betterment of human health, environmental sustainability, and global progress.',
            'Join us as we embark on this exciting journey at the forefront of computational biology, pushing the boundaries of knowledge and innovation in our relentless pursuit of excellence.'
        ]
    }
    return render(request, 'template-kush.html', {'content': content})


def projectsrender(request):
    return render(request, 'projects/projects.html')


# def loginrender(request):
#     return render(request, 'registration/login.html')


def contactrender(request):
    return render(request, 'contact/contact-kush.html')


def facultyrender(request):
    return render(request, 'static/people/core-faculty.html')


def collabrender(request):
    return render(request, 'static/people/collab.html')


def missionrender(request):
    return render(request, 'static/mission/mission.html')


def generender(request):
    questions = Question.objects.all()
    return render(request, 'gene-chat.html', {'questions': questions})


def question_create_view(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES)
        if form.is_valid():
            question = form.save(commit=False)
            question.created_by = request.user
            # question.given_to = request.user
            question.save()

            for f in request.FILES.getlist('file_field'):
                QuestionFile.objects.create(file=f, question=question)

            return redirect('generender')
    else:
        form = QuestionForm()
    return render(request, 'create_question.html', {'form': form})


def answer_create_view(request, question_id):
    question = Question.objects.get(id=question_id)
    if request.method == 'POST':
        form = AnswerForm(request.POST, request.FILES)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.created_by = request.user
            answer.question = question
            answer.save()

            for f in request.FILES.getlist('file_field'):
                AnswerFile.objects.create(file=f, answer=answer)

            return redirect('htmlrender', question_id=question_id)
    else:
        form = AnswerForm()
    return render(request, 'create_answer.html', {'form': form})


@login_required
def profilerender(request):
    return render(request, 'profile/profile.html')

biotechwebsite/biotech/templates/carousel.html
{% load static %}
<input type="radio" id="image1" name="image" checked>
<input type="radio" id="image2" name="image">
<input type="radio" id="image3" name="image">

<div class="container">
    <div class="featured-wrapper">
        <ul class="featured-list">
            <li>
                <figure>
                    <img src="{% static '../static/biotech/images/c1.png' %}">
                    <figcaption>
                        <h3>iBioML</h3>
                        <h2>BIOINFORMATICS</h2>
                        <hr>
                        <p>University of Washington Bothell: Pioneering Advances in Bioinformatics</p>
                        <p>Bridging Biology, Computer Science, and Information Technology to Drive Innovation and
                            Discovery in Genomic Research.</p>
                        <button class="view-program-btn" onclick="viewProjects()"><span class="button-text">VIEW
                                PROJECTS</span></button>
                    </figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <img src="{% static '../static/biotech/images/c2.jpeg' %}">
                    <figcaption>
                        <h3>iBioML</h3>
                        <h2>GENE CHAT</h2>
                        <hr>
                        <p>Collaboration is the essence of coding. It's a collective intelligence that turns
                            individual lines of code into software that changes the world.</p>
                        <p>A platform to provide answers and code to datasets and questions posted by graduate
                            students and faculty.</p>
                        <button class="view-program-btn" onclick="viewChat()"><span class="button-text">GENE
                                CHAT</span></button>
                    </figcaption>
                </figure>
            </li>
            <li>
                <figure>
                    <img src="{% static '../static/biotech/images/c3.jpg' %}">
                    <figcaption>
                        <h3>iBioML</h3>
                        <h2>FACULTY</h2>
                        <hr>
                        <p>Architects of the future, shaping the minds to innovate</p>
                        <p>Check out the cutting edge faculty associated with BioInformatics at University of
                            Washington Bothell.</p>
                        <button class="view-program-btn" onclick="viewFaculty()"><span class="button-text">GO TO
                                FACULTY</span></button>
                    </figcaption>
                </figure>
            </li>
        </ul>
        <ul class="arrows">
            <li>
                <label for="image1"></label>
            </li>
            <li>
                <label for="image2"></label>
            </li>
            <li>
                <label for="image3"></label>
            </li>
        </ul>
        <ul class="dots">
            <li>
                <label for="image1"></label>
            </li>
            <li>
                <label for="image2"></label>
            </li>
            <li>
                <label for="image3"></label>
            </li>
        </ul>
    </div>
</div>

biotechwebsite/biotech/templates/create_answer.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Create Answer</title>
</head>

<body>
    {% block content %}
    <h2>Post an answer</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Post answer</button>
    </form>
    {% endblock %}
</body>

</html>

biotechwebsite/biotech/templates/create_question.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Question Create</title>
</head>

<body>

    {% block content %}
    <h2>Post a new question</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Post question</button>
    </form>
    {% endblock %}
</body>

</html>

biotechwebsite/biotech/templates/gene-chat.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>iBioML Gene Chat | University of Washington Bothell</title>
    <!-- {% load static %} -->
    <!-- <link rel="stylesheet" type="text/css" href="{% static '../static/biotech/index.css' %}"> -->
</head>

<body>
    <!-- {% include 'header/header.html' %} -->

    <!-- <h1>G E N E C H A T</h1> -->

    {% block content %}
    {% load group_filters %}

    <h2>Questions</h2>

    {% if user.is_authenticated %}

    {% if user|is_in_group:"Domain Expert" or user.is_superuser %}

    <p><a href="{% url 'create_question' %}">Post a new project</a></p>

    {% endif %}
    {% endif %}

    <p>x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-</p>


    {% for question in questions %}
    <div>
        <h3>{{ question.title }}</h3>
        <p>{{ question.content }}</p>

        {% if user.is_authenticated %}
        {% if user|is_in_group:"Practitioner" or user.is_superuser %}

        <p><a href="{{ question.file.url }}">Download file</a></p>

        {% endif %}
        {% endif %}

        <h4>Answers:</h4>
        {% for answer in question.answer_set.all %}
        <p>{{ answer.content }}</p>

        {% if user.is_authenticated %}
        {% if user|is_in_group:"Practitioner" or user.is_superuser %}

        <p><a href="{{ answer.file.url }}">Download file</a></p>

        {% endif %}
        {% endif %}

        {% empty %}

        <!-- <p>No answers yet.</p> -->

        {% if user.is_authenticated %}
        {% if user|is_in_group:"Practitioner" or user.is_superuser %}
        <!-- {% if user.username == question.given_to} -->

        <p><a href="{% url 'create_answer' question_id=question.id %}">Post an answer</a></p>

        {% endif %}
        {% endif %}

        {% endfor %}

    </div>
    <p>x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-x-</p>

    {% empty %}
    <p>No questions yet.</p>
    {% endfor %}
    {% endblock %}

    <!-- <div style="height: 20vh;"></div> -->

    <!-- {% include 'footer/footer.html' %} -->
</body>

</html>

biotechwebsite/biotech/templates/template-kush.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <title>iBioML | University of Washington Bothell</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static '../static/biotech/index.css' %}">
</head>

<body>

    {% include 'header/header.html' %}

    {% include 'carousel.html' %}

    <!-- <section class="homecontent">
        <h2>{{ content.title }}</h2><br><br>
        {% for paragraph in content.paragraphs %}
        <p>{{ paragraph }}</p><br><br>
        {% endfor %}
    </section> -->
    <br>
    <section class="purple-section">
        <div class="text-container">
            <h3>iBIOML PROJECTS</h3>
            <hr>
            <p>
                Our main research area is pattern recognition in bioinformatics, especially, biological motif analysis.
                We developed various bioinformatics tools online.
            </p>

        </div>

        <div class="image-container">
            <img src="../static/biotech/images/projects.jpeg">
            <button class="view-program-btn" onclick="viewProjects()"><span class="button-text">VIEW
                    PROJECTS</span></button>
        </div>
        <script>
            function viewProjects() {
                window.location.href = 'projects/'
            }
        </script>
    </section>
    <br><br><br>
    <section class="purple-section">
        <div class="text-container">
            <h3>GENE CHAT</h3>
            <hr>
            <p>
                Discussion Board for students and collaborators to publish projects and datasets.
            </p>

        </div>

        <div class="image-container">
            <img src="../static/biotech/images/genechat.jpeg">
            <button class="view-program-btn" onclick="viewChat()"><span class="button-text">GO TO GENE
                    CHAT</span></button>
        </div>
        <script>
            function viewProjects() {
                window.location.href = "{% url 'projectsrender' %}"
            }
            function viewChat() {
                window.location.href = "{% url 'generender' %}"
            }
            function viewFaculty() {
                window.location.href = "{% url 'facultyrender' %}"
            }
        </script>
    </section>

    <br><br><br>

    <h2>Watch Our Video To Learn How To Surf On This Website. </h2>

    <br><br>

    <div class="button-container">
        <button class="button-50" role="button"
            onclick="window.open('https://www.youtube.com/watch?v=qEVUtrk8_B4', '_blank');" target="_blank">
            <span class="button-text">WATCH VIDEO</span>
        </button>
    </div>
    <br><br><br><br>

    {% include 'footer/footer.html' %}
</body>

</html>